name: '[Test] Onboarding application'
description: Information necessary to determine eligibility and required contributions
title: "owner/repo"
labels: [ 'project application' ]
assignees:
  - aleks-ivanov
  - kulov
  - ross-bohr
  - szlatkow
body:
  - type: markdown
    attributes:
      value: |
        # 1.  Project Information
  - type: input
    id: project-name
    attributes:
      label: 'Project Name:'
    validations:
      required: true
  - type: input
    id: github-url
    attributes:
      label: 'GitHub URL:'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Project description:'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # 2.  Contact person
  - type: input
    id: cp-name
    attributes:
      label: 'Name:'
    validations:
      required: true
  - type: input
    id: cp-email
    attributes:
      label: 'Email:'
    validations:
      required: true
  - type: input
    id: cp-gh-profile
    attributes:
      label: 'GitHub Profile URL:'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # 3.  Eligibility criteria
        
        Please complete the following for your project:
  - type: checkboxes
    id: build-instructions
    attributes:
      label: Project has build instructions
      description: Does the project have `Contributors guide` or build pipeline/script
      options:
        - label: 'Yes'
          required: false









  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
