name: Create new project from issue

on: 
  issues:
    types: [ opened ]

jobs:
  data:
    name: Data gathering
    runs-on: ubuntu-20.04
    environment: application_submission
    outputs:
      proj_original_repo: ${{ steps.project_info.outputs.proj_original_repo }}
      proj_name: ${{ steps.project_info.outputs.proj_name }}
    steps:
      - name: Project information
        id: project_info
        shell: pwsh
        run: |
          $projOriginalRepo = "${{ github.event.issue.title }}"
          $projName = $projOriginalRepo.Split('/')[1]

          echo "::set-output name=proj_original_repo::$(echo $projectOriginalRepo)"
          echo "::set-output name=proj_name::$(echo $projectName)"

  create-forks:
    needs: data
    name: Create forks
    uses: pipeline-foundation/projects/.github/workflows/create-forks.yml@master
    with:
      proj_original_repo: ${{ needs.data.outputs.proj_original_repo }}
      proj_name: ${{ needs.data.outputs.proj_name }}

  add-dbot:
    needs: data, create-forks
    name: Add Dependabot
    uses: pipeline-foundation/projects/.github/workflows/add-dbot.yml@master
    with:
      repo: ${{ needs.data.outputs.proj_name }}