name: Create new project from issue

on: 
  issues:
    types: [ opened ]

jobs:
  create-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Execute fork creation
        id: execute_fork_creation
        shell: pwsh
        run: |
          $projectRepo = "${{ github.event.issue.title }}"
          $projectName = $projectRepo.Substring(($projectRepo.IndexOf('/') + 1))
          $pfRepo = "pipeline-foundation/$projectName"

          Write-Output "`n`nCommencing Pipeline Foundation fork creation...`n`n"

          Start-Job -Name Create_PF_Fork -ScriptBlock {
            $newProject = "https://api.github.com/repos/$Using:projectRepo/forks"
            $basicBase64Token = "${{ secrets.PF_ACCESS_BASE64_BASIC_TOKEN }}"
            $headers = @{
              'Accept'        = 'application/vnd.github.v3+json';
              'Authorization' = "Basic {0}" -f $basicBase64Token;
            }
            $body = @{
              organization = 'pipeline-foundation'
            } | ConvertTo-Json

            Invoke-RestMethod -Method POST -Headers $headers -Uri $newProject -Body $body
          }

          Wait-Job -Name Create_PF_Fork

          Write-Output "`n`nPipeline Foundation fork created!`n`n"

          Write-Output "`n`nCommencing Pipeline Foundation fork branches creation...`n`n"

          Start-Job -Name Create_PF_Fork_Branches -ScriptBlock {
            $branchesArr = @(
              'dependabot',
              'codeql',
              'ci-cd'
            )
            $pfUri = "https://api.github.com/repos/$Using:pfRepo"
            $defaultBranch = Invoke-RestMethod -Method GET -Uri $pfUri | Select-Object -ExpandProperty default_branch

            git clone https://token:${{ secrets.PF_ACCESS_TOKEN }}@github.com/$Using:pfRepo.git
            Push-Location $Using:projectName
            git checkout $defaultBranch
            foreach ($branch in $branchesArr) {
              git branch feature/$branch
              git checkout feature/$branch
              git push origin feature/$branch
              git checkout $defaultBranch
            }
          }

          Wait-Job -Name Create_PF_Fork_Branches

          Write-Output "`n`nPipeline Foundation fork branches created!`n`n"

          Write-Output "`n`nCommencing members fork creation...`n`n"

          Start-Job -Name Create_Mambers_Forks -ScriptBlock {
            $membersArr = @(
              [pscustomobject]@{ name = "aleks-ivanov"; token = "${{ secrets.ALEKS_IVANOV_GITHUB_TOKEN }}" }
            )
            $pfProjectFork = "https://api.github.com/repos/$Using:pfRepo/forks"

            foreach ($member in $membersArr) {
              $memberName = $member.name
              $memberToken = $member.token
              $basicToken = "${memberName}:${memberToken}"
              $basicBase64Token = [System.Convert]::ToBase64String([char[]]$basicToken)
              $headers = @{
                'Accept'        = 'application/vnd.github.v3+json';
                'Authorization' = "Basic {0}" -f $basicBase64Token;
              }
              $body = @{
                owner = 'aleks-ivanov'
              } | ConvertTo-Json

              Invoke-RestMethod -Method POST -Headers $headers -Uri $pfProjectFork -Body $body
            }
          }

          Wait-Job -Name Create_Mambers_Forks

          Write-Output "`n`nMembers fork created!`n`n"