name: Create new project from issue

on: 
  issues:
    types: [ opened ]

jobs:
  data:
    name: Data gathering
    runs-on: ubuntu-20.04
    environment: application_submission
    outputs:
      proj_original_repo: ${{ steps.project_info.outputs.proj_original_repo }}
      proj_name: ${{ steps.project_info.outputs.proj_name }}
    steps:
      - name: Project information
        id: project_info
        shell: pwsh
        run: |
          $projOriginalRepo = "${{ github.event.issue.title }}"
          $projName = $projOriginalRepo.Split('/')[1]

          echo "::set-output name=proj_original_repo::$(echo $projOriginalRepo)"
          echo "::set-output name=proj_name::$(echo $projName)"

  create-forks:
    needs: data
    name: Create forks
    uses: pipeline-foundation/reusable-workflows/.github/workflows/create-forks.yml@v1.0.0
    with:
      proj_original_repo: ${{ needs.data.outputs.proj_original_repo }}
      proj_name: ${{ needs.data.outputs.proj_name }}
    secrets:
      azdo_token: ${{ secrets.ISSUE_TO_AZDO_WORKITEM }}
      pf_token: ${{ secrets.PF_ACCESS_TOKEN }}
      pf_token_64: ${{ secrets.PF_ACCESS_BASE64_BASIC_TOKEN }}
      aivanov_token: ${{ secrets.ALEKS_IVANOV_GITHUB_TOKEN }}
      szlatkow_token: ${{ secrets.SZLATKOW_GITHUB_TOKEN }}

  add-dbot:
    needs: [ data, create-forks ]
    name: Add Dependabot
    uses: pipeline-foundation/reusable-workflows/.github/workflows/add-dbot.yml@v1.0.0
    with:
      repo: ${{ needs.data.outputs.proj_name }}
    secrets:
      aivanov_token: ${{ secrets.ALEKS_IVANOV_GITHUB_TOKEN }}
      szlatkow_token: ${{ secrets.SZLATKOW_GITHUB_TOKEN }}