name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [ edited ]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ISSUE_TO_AZDO_WORKITEM }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          ado_organization: "singlet-dev"
          ado_project: "Pipeline Foundation"
          ado_area_path: "Pipeline Foundation\\General"
          ado_iteration_path: "Pipeline Foundation"
          ado_wit: "${{ github.event.issue.title }} - contribution"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
