name: Test workflow_call

on:
  push:
    paths:
      - '.github/workflows/workflowcall_test.yml'
  workflow_dispatch:

jobs:
  add-dbot:
    uses: pipeline-foundation/projects/.github/workflows/add-dbot.yml@master
    with:
      repo: asddfgqw